[package]
name = "reinlinsen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = "0.14.0"
docker-api = "0.13.0"
futures = "0.3.28"
tokio = { version = "1.28.0", features = ["full"] }
